[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12, <3.13"
pandas = "^2.2.3"
jupyter = "^1.1.1"
openpyxl = "^3.1.5"
matplotlib = "^3.9.2"
tqdm = "^4.67.0"
geopy = "^2.4.1"
folium = "^0.18.0"
